version: '3.4'

services:
  chat_service:
    image: chat_service:latest
    ports: 
      - "44345:80"
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
  redis:
    image: bitnami/redis
    deploy:
        replicas: 1
    ports:
      - "6379:6379"
    environment: 
      REDIS_PASSWORD: "password123"